services:
  postgres:
    image: postgres:16
    container_name: moneyfy-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: moneyfy_user
      POSTGRES_PASSWORD: moneyfy_password
      POSTGRES_DB: moneyfy_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: moneyfy-redis
    restart: always
    ports:
      - "6379:6379"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: moneyfy-server
    restart: always
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DATABASE_URL: postgresql://moneyfy_user:moneyfy_password@postgres:5432/moneyfy_db?schema=public
      JWT_SECRET: moneyfy_super_secret_key
      JWT_EXPIRES_IN: 1d
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: moneyfy-client
    restart: always
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    depends_on:
      - server  

volumes:
  postgres_data: